### ISSUE TITLE
2024 Roadmap

### ISSUE THREAD

**Issue by veighna-global** [veighna-global/vnpy_crypto#33]
Hello guys, not sure how many are still following the updates of this project.

We are making lots of improvements now, mostly a redesigned quant trading platfrom which only focuses on the crypto market, i.e. remove those unrelated parts of the original VeighNa project.

Here is our roadmap for 2024, please let us know if you have any suggestions!

**Comment by veighna-global** [comment]
- [ ] 0.1.0
   - [ ] provide same API as the original vnpy project (for modules/classes/functions)
   - [ ] implement a new Fluent-Design UI
   - [ ] update BINANCE trading gateway module (vnpy_binance)
- [ ] 0.2.0
   - [ ] implement new quant strategy modules for crypto markets (both backtesting and trading)
   - [ ] update OKX trading gateway module (vnpy_okx) 
- [ ] 0.3.0
   - [ ] release the first version of documents, maybe also a new official website
   - [ ] update Bybit trading gateway module (vnpy_bybit)

**Comment by laye0619** [comment]
Hello Veighna, I am using your OKX and MT5 API for a long period of time. Glad to see you have continuation plan for this. May I ask if you have any plan for MT5 gateway?

**Comment by veighna-global** [comment]
> Hello Veighna, I am using your OKX and MT5 API for a long period of time. Glad to see you have continuation plan for this. May I ask if you have any plan for MT5 gateway?

Sure, I will add MT5 on to the roadmap. Please let more people know we are starting to update now.

**Comment by veighna-global** [comment]
New milestone! First version (0.1.0) of VeighNa Evo has been released.

**Comment by veighna-global** [comment]
> Hello Veighna, I am using your OKX and MT5 API for a long period of time. Glad to see you have continuation plan for this. May I ask if you have any plan for MT5 gateway?

vnpy_mt5 has been updated to VeighNa Evo version, please hava a look:

https://github.com/veighna-global/vnpy_mt5

**Comment by laye0619** [comment]
> > Hello Veighna, I am using your OKX and MT5 API for a long period of time. Glad to see you have continuation plan for this. May I ask if you have any plan for MT5 gateway?
> 
> vnpy_mt5 has been updated to VeighNa Evo version, please hava a look:
> 
> https://github.com/veighna-global/vnpy_mt5

Actually, MT5 gateway should have a potential problem. Different forex brokers have different timezones, which I cannot set in the current version of the MT5 gateway file. For me, I have three different forex brokers, which means three MT5 terminals connected to three vnpy terminals while the same gateway is used. I have to modify the gateway as well as the MT5 EA, querying the broker name and setting different timezones for time conversion.

The trading time is another significant issue. The bar generator must be changed for each broker.

Overall, I have to modify the code to adapt it. I was wondering if your official side could provide a comprehensive solution to resolve these issues.

Thanks.

**Comment by laye0619** [comment]
> > > Hello Veighna, I am using your OKX and MT5 API for a long period of time. Glad to see you have continuation plan for this. May I ask if you have any plan for MT5 gateway?
> > 
> > 
> > vnpy_mt5 has been updated to VeighNa Evo version, please hava a look:
> > https://github.com/veighna-global/vnpy_mt5
> 
> Actually, MT5 gateway should have a potential problem. Different forex brokers have different timezones, which I cannot set in the current version of the MT5 gateway file. For me, I have three different forex brokers, which means three MT5 terminals connected to three vnpy terminals while the same gateway is used. I have to modify the gateway as well as the MT5 EA, querying the broker name and setting different timezones for time conversion.
> 
> The trading time is another significant issue. The bar generator must be changed for each broker.
> 
> Overall, I have to modify the code to adapt it. I was wondering if your official side could provide a comprehensive solution to resolve these issues.
> 
> Thanks.

or this should be posted in MT5 repository?

**Comment by LotuSrc** [comment]
In v0.3.0 implement new quant strategy modules for crypto markets (both backtesting and trading), will this version support portfolio strategy?

**Comment by veighna-global** [comment]
> In v0.3.0 implement new quant strategy modules for crypto markets (both backtesting and trading), will this version supports portfolio strategy?

Yes, we would prefer one strategy module that can support different types of strategies as much as possible.

Compared with the original VeighNa team, they prefer to provide different modules for each type of strategy.

**Comment by ItVen** [comment]
请问Gate.io 现在能支持了吗
